version: "3.9"
services:

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url_shortcut
      - PGDATA=/var/lib/postgresql/url_shortcut
    volumes:
      - ./db/url_shortcut:/var/lib/postgresql/url_shortcut
    restart: always

  shortcut:
    container_name: shortcut
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url_shortcut
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db